### ISSUE TITLE
help me please

### ISSUE THREAD

**Issue by Minhe173** [spinfal/temporary-email-bot#3]
@spinfal 
```C:\Users\dell\Downloads\temporary-email-bot-master\temporary-email-bot-master\node_modules\discord.js\src\client\Client.js:480
      throw new TypeError(ErrorCodes.ClientMissingIntents);
      ^

TypeError [ClientMissingIntents]: Valid intents must be provided for the Client.
    at Client._validateOptions (C:\Users\dell\Downloads\temporary-email-bot-master\temporary-email-bot-master\node_modules\discord.js\src\client\Client.js:480:13)   
    at new Client (C:\Users\dell\Downloads\temporary-email-bot-master\temporary-email-bot-master\node_modules\discord.js\src\client\Client.js:78:10)
    at Object.<anonymous> (C:\Users\dell\Downloads\temporary-email-bot-master\temporary-email-bot-master\index.js:7:16)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'ClientMissingIntents'
}```

**Comment by Minhe173** [comment]
@spinfal

**Comment by Minhe173** [comment]
@spinfal
